### ISSUE TITLE
Expand Support for Python 3.8+ and Django 4.2+

### ISSUE THREAD

**Issue by sepehr-akbarzadeh** [sageteam-org/django-iranian-cities#10]
**Summary:**
We need to ensure that our project supports Python versions from 3.6 and above and Django versions from 3.2 and above. This will involve updating our dependencies, testing frameworks, and documentation to confirm compatibility with these versions.

**Details:**

1. **Python Support:**
   - Extend support to include Python 3.6, 3.7, 3.8, 3.9, and above.
   - Update our codebase to be compatible with these versions.
   - Modify CI/CD pipelines to test against these Python versions.
   - Ensure all dependencies used are compatible with the specified Python versions.
   - Update documentation to reflect the supported Python versions.

2. **Django Support:**
   - Extend support to include Django 3.2 and above.
   - Ensure our project and any dependencies are compatible with Django 3.2 and above.
   - Update any deprecated methods or functions as per the Django upgrade guide.
   - Modify CI/CD pipelines to test against these Django versions.
   - Update documentation to reflect the supported Django versions.

3. **Testing:**
   - Thoroughly test the application on all supported Python and Django versions.
   - Address any compatibility issues that arise during testing.
   - Ensure that automated tests cover the new versions.

4. **Dependencies:**
   - Review all dependencies for compatibility with the new versions of Python and Django.
   - Update any dependencies that do not support the new versions.
   - Document any dependencies that cannot be upgraded and require workarounds.

5. **Documentation:**
   - Update all relevant documentation to indicate the newly supported Python and Django versions.
   - Provide guidelines for developers to set up their development environments for the new versions.
   - Update any code examples in the documentation to be compatible with the new versions.

**Acceptance Criteria:**
- The project should run without issues on Python 3.6 and above.
- The project should run without issues on Django 3.2 and above.
- All tests should pass across all supported versions.
- Documentation should be updated and clear on the supported versions and any required setup steps.

**Additional Context:**
If there are any significant changes or challenges encountered during this update, they should be documented and discussed to find appropriate solutions.

**Comment by sepehr-akbarzadeh** [comment]
@ARYAN-NIKNEZHAD Did you check this?

**Comment by ARYAN-NIKNEZHAD** [comment]
@sepehr-akbarzadeh 
Django no longer supports version 3
And we go with 4
The rest of the work has been done

Close the issue
