### ISSUE TITLE
Add Sphinx Documentation for django-iranian-cities Package

### ISSUE THREAD

**Issue by sepehr-akbarzadeh** [sageteam-org/django-iranian-cities#11]
**Summary:**
We need to create comprehensive Sphinx documentation for the `django-iranian-cities` package to improve its usability and maintainability. This will involve setting up Sphinx, writing detailed documentation for the package's features, modules, and usage, and ensuring the documentation is well-organized and accessible.

**Details:**

1. **Set Up Sphinx:**
   - Install Sphinx and any necessary extensions (e.g., `sphinx_rtd_theme`).
   - Create a `docs` directory in the project root.
   - Initialize Sphinx in the `docs` directory.

2. **Configuration:**
   - Configure `conf.py` to include necessary extensions and set up the project details.
   - Set the documentation theme to `sphinx_rtd_theme` or another appropriate theme.

3. **Write Documentation:**
   - **Introduction:**
     - Overview of the `django-iranian-cities` package.
     - Features and capabilities.
   - **Installation:**
     - Step-by-step installation guide.
     - Dependencies and requirements.
   - **Usage:**
     - Detailed usage instructions.
     - Code examples and snippets.
   - **API Reference:**
     - Auto-generate API documentation using Sphinx autodoc.
     - Document all modules, classes, methods, and functions.
   - **Configuration:**
     - Document any configuration options and settings.
   - **Contributing:**
     - Guidelines for contributing to the project.
   - **Changelog:**
     - Maintain a changelog to document version history and changes.

4. **Build Documentation:**
   - Build HTML documentation and ensure it displays correctly.
   - Fix any issues or warnings that arise during the build process.

5. **Integrate with CI/CD:**
   - Add steps to the CI/CD pipeline to build and deploy the documentation.
   - Ensure the documentation is automatically updated with new releases.

6. **Review and Feedback:**
   - Review the documentation for accuracy and completeness.
   - Request feedback from other developers and users.

**Acceptance Criteria:**
- Sphinx is set up and configured correctly in the `docs` directory.
- Comprehensive documentation is written and organized logically.
- The documentation builds without errors or warnings.
- The documentation is integrated into the CI/CD pipeline for automatic updates.
- Feedback is incorporated, and the documentation is reviewed for accuracy.

**Comment by sepehr-akbarzadeh** [comment]
@ARYAN-NIKNEZHAD  Would you please update the Sphinx documentation of this package?

**Comment by ARYAN-NIKNEZHAD** [comment]
@sepehr-akbarzadeh 
I already did
pull request #37 

Close the Issue
