### ISSUE TITLE
ugettext_lazy can not be imported

### ISSUE THREAD

**Issue by vhdmoradi** [sageteam-org/django-iranian-cities#4]
I was trying to install and use this package. After installing and adding the app to INSTALLED_APPS, when trying to run command "makemigrations", returns this error:
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'

**Comment by AshkanVakili9** [comment]
hay just go to 'django.utils.translation' and change it to 'gettext_lazy '

**Comment by ghazalmohseni7** [comment]
> hay just go to 'django.utils.translation' and change it to 'gettext_lazy '

in translation folder , which py file should be renamed to "gettext_lazy" ?

**Comment by arminshfatemi** [comment]
any update on this issue ?

**Comment by sepehr-akbarzadeh** [comment]
we will check and fix the problem.
@arminshfatemi 

thanks for contributing

**Comment by ARYAN-NIKNEZHAD** [comment]
We’re happy to announce v2.0.0 of django-iranian-cities!
