### ISSUE TITLE
integer out of range

### ISSUE THREAD

**Issue by HosseinFattahi** [sageteam-org/django-iranian-cities#52]
you can fix this issue with change IntegerField in model from "amar_code" to PositiveBigIntegerField like:
amar_code = models.PositiveBigIntegerField(_('Amar Code'))

**Comment by sepehr-akbarzadeh** [comment]
Hi there,

What was the problem?

**Comment by HosseinFattahi** [comment]
hey,you use integer field for amar_code and your amar code is biger than integer so when i want migrate its give me eror max lengh.
so you should use PositiveBigIntegerField

**Comment by ARYAN-NIKNEZHAD** [comment]
In our recent update, we have completely revamped the code, and this task is no longer required.

Thank you for your cooperation!
